#数据库配置
spring:
  datasource:
    url: jdbc:mysql://10.0.75.1:3306/brian?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 258wan
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#配置redis数据库
  redis:
    host: 10.0.75.1
#配置rabbitMQ
  rabbitmq:
    host: 10.0.75.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    #值为true可实现消息确认
    publisher-confirms: true

#指定bean所在包
mybatis:
  type-aliases-package: com.kawa.pojo
#指定映射文件
  mapper-locations: classpath:mapper/*.xml



